version: "3.9"

services:
  web:
    tty: true
    image: node:16
    restart: always
    ports:
      - "49160:8080"
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
